// Mapa de países com suas respectivas siglas (3 letras) e URLs de bandeiras
const PAISES_MAPA = {
  'Alemanha': { sigla: 'ALE', codigo: 'de' },
  'Argentina': { sigla: 'ARG', codigo: 'ar' },
  'Austrália': { sigla: 'AUS', codigo: 'au' },
  'Bélgica': { sigla: 'BEL', codigo: 'be' },
  'Brasil': { sigla: 'BRA', codigo: 'br' },
  'Canadá': { sigla: 'CAN', codigo: 'ca' },
  'Colômbia': { sigla: 'COL', codigo: 'co' },
  'Costa Rica': { sigla: 'CRC', codigo: 'cr' },
  'Croácia': { sigla: 'CRO', codigo: 'hr' },
  'Dinamarca': { sigla: 'DIN', codigo: 'dk' },
  'Egito': { sigla: 'EGI', codigo: 'eg' },
  'Escócia': { sigla: 'ESC', codigo: 'gb-sct' },
  'Espanha': { sigla: 'ESP', codigo: 'es' },
  'Estados Unidos': { sigla: 'EUA', codigo: 'us' },
  'Equador': { sigla: 'EQU', codigo: 'ec' },
  'Eslováquia': { sigla: 'ESK', codigo: 'sk' },
  'Eslovênia': { sigla: 'ESN', codigo: 'si' },
  'Estônia': { sigla: 'EST', codigo: 'ee' },
  'Finlândia': { sigla: 'FIN', codigo: 'fi' },
  'França': { sigla: 'FRA', codigo: 'fr' },
  'Gales': { sigla: 'GAL', codigo: 'gb-wls' },
  'Gana': { sigla: 'GNA', codigo: 'gh' },
  'Grécia': { sigla: 'GRE', codigo: 'gr' },
  'Guadalupe': { sigla: 'GLP', codigo: 'gp' },
  'Guatemala': { sigla: 'GUA', codigo: 'gt' },
  'Guiana': { sigla: 'GUI', codigo: 'gy' },
  'Guiné': { sigla: 'GUN', codigo: 'gn' },
  'Holanda': { sigla: 'HOL', codigo: 'nl' },
  'Honduras': { sigla: 'HON', codigo: 'hn' },
  'Hong Kong': { sigla: 'HKG', codigo: 'hk' },
  'Hungria': { sigla: 'HUN', codigo: 'hu' },
  'Índia': { sigla: 'IND', codigo: 'in' },
  'Indonésia': { sigla: 'INO', codigo: 'id' },
  'Inglaterra': { sigla: 'ING', codigo: 'gb-eng' },
  'Irã': { sigla: 'IRA', codigo: 'ir' },
  'Irlanda': { sigla: 'IRL', codigo: 'ie' },
  'Irlanda do Norte': { sigla: 'IRN', codigo: 'gb-nir' },
  'Islândia': { sigla: 'ISL', codigo: 'is' },
  'Israel': { sigla: 'ISR', codigo: 'il' },
  'Itália': { sigla: 'ITA', codigo: 'it' },
  'Jamaicá': { sigla: 'JAM', codigo: 'jm' },
  'Japão': { sigla: 'JAP', codigo: 'jp' },
  'Jordânia': { sigla: 'JOR', codigo: 'jo' },
  'Letônia': { sigla: 'LET', codigo: 'lv' },
  'Líbano': { sigla: 'LIB', codigo: 'lb' },
  'Líbia': { sigla: 'LBA', codigo: 'ly' },
  'Lituânia': { sigla: 'LIT', codigo: 'lt' },
  'Luxemburgo': { sigla: 'LUX', codigo: 'lu' },
  'Macedônia': { sigla: 'MAC', codigo: 'mk' },
  'Malásia': { sigla: 'MAL', codigo: 'my' },
  'Mali': { sigla: 'MLI', codigo: 'ml' },
  'Marrocos': { sigla: 'MAR', codigo: 'ma' },
  'Martinica': { sigla: 'MAT', codigo: 'mq' },
  'Maurício': { sigla: 'MRC', codigo: 'mu' },
  'México': { sigla: 'MEX', codigo: 'mx' },
  'Moçambique': { sigla: 'MOZ', codigo: 'mz' },
  'Moldávia': { sigla: 'MOD', codigo: 'md' },
  'Mongólia': { sigla: 'MON', codigo: 'mn' },
  'Montenegro': { sigla: 'MNT', codigo: 'me' },
  'Namíbia': { sigla: 'NAM', codigo: 'na' },
  'Nigéria': { sigla: 'NIG', codigo: 'ng' },
  'Noruega': { sigla: 'NOR', codigo: 'no' },
  'Nova Zelândia': { sigla: 'NZL', codigo: 'nz' },
  'Omã': { sigla: 'OMA', codigo: 'om' },
  'Pakistão': { sigla: 'PAK', codigo: 'pk' },
  'Panamá': { sigla: 'PAN', codigo: 'pa' },
  'Papua Nova Guiné': { sigla: 'PNG', codigo: 'pg' },
  'Paraguai': { sigla: 'PAR', codigo: 'py' },
  'Peru': { sigla: 'PER', codigo: 'pe' },
  'Polônia': { sigla: 'POL', codigo: 'pl' },
  'Porto Rico': { sigla: 'PRC', codigo: 'pr' },
  'Portugal': { sigla: 'POR', codigo: 'pt' },
  'Quênia': { sigla: 'QUE', codigo: 'ke' },
  'Quirguistão': { sigla: 'KGZ', codigo: 'kg' },
  'República Centro-Africana': { sigla: 'RCA', codigo: 'cf' },
  'República Checa': { sigla: 'RTC', codigo: 'cz' },
  'República Dominicana': { sigla: 'RDO', codigo: 'do' },
  'República Tcheca': { sigla: 'RTC', codigo: 'cz' },
  'Ruanda': { sigla: 'RUA', codigo: 'rw' },
  'Romênia': { sigla: 'ROM', codigo: 'ro' },
  'Rússia': { sigla: 'RUS', codigo: 'ru' },
  'Salvadora': { sigla: 'SAL', codigo: 'sv' },
  'Samoa': { sigla: 'SAM', codigo: 'ws' },
  'San Marino': { sigla: 'SMR', codigo: 'sm' },
  'Santa Lúcia': { sigla: 'SLU', codigo: 'lc' },
  'São Cristóvão e Névis': { sigla: 'SKN', codigo: 'kn' },
  'São Marinho': { sigla: 'SMR', codigo: 'sm' },
  'São Tomé e Príncipe': { sigla: 'STP', codigo: 'st' },
  'São Vicente e Granadinas': { sigla: 'SVG', codigo: 'vc' },
  'Senegal': { sigla: 'SEN', codigo: 'sn' },
  'Sérvia': { sigla: 'SRB', codigo: 'rs' },
  'Seicheles': { sigla: 'SEI', codigo: 'sc' },
  'Singapura': { sigla: 'SIN', codigo: 'sg' },
  'Síria': { sigla: 'SIR', codigo: 'sy' },
  'Somália': { sigla: 'SOM', codigo: 'so' },
  'Sri Lanka': { sigla: 'SRL', codigo: 'lk' },
  'Suazilândia': { sigla: 'SWZ', codigo: 'sz' },
  'Sudão': { sigla: 'SUD', codigo: 'sd' },
  'Sudão do Sul': { sigla: 'SDS', codigo: 'ss' },
  'Suécia': { sigla: 'SUE', codigo: 'se' },
  'Suíça': { sigla: 'SUI', codigo: 'ch' },
  'Surinã': { sigla: 'SUR', codigo: 'sr' },
  'Tailândia': { sigla: 'TAI', codigo: 'th' },
  'Taiwan': { sigla: 'TAW', codigo: 'tw' },
  'Tadjiquistão': { sigla: 'TAD', codigo: 'tj' },
  'Tanzânia': { sigla: 'TAN', codigo: 'tz' },
  'Terceira e Príncipe': { sigla: 'STP', codigo: 'st' },
  'Timor Leste': { sigla: 'TLS', codigo: 'tl' },
  'Togo': { sigla: 'TOG', codigo: 'tg' },
  'Trinidad e Tobago': { sigla: 'TTO', codigo: 'tt' },
  'Tunísia': { sigla: 'TUN', codigo: 'tn' },
  'Turquemenistão': { sigla: 'TKM', codigo: 'tm' },
  'Turquia': { sigla: 'TUR', codigo: 'tr' },
  'Tuvalú': { sigla: 'TUV', codigo: 'tv' },
  'Ucrânia': { sigla: 'UCR', codigo: 'ua' },
  'Uganda': { sigla: 'UGA', codigo: 'ug' },
  'Uruguai': { sigla: 'URU', codigo: 'uy' },
  'Uzbequistão': { sigla: 'UZB', codigo: 'uz' },
  'Vanuatu': { sigla: 'VAN', codigo: 'vu' },
  'Vaticano': { sigla: 'VAT', codigo: 'va' },
  'Venezuela': { sigla: 'VEN', codigo: 've' },
  'Vietnã': { sigla: 'VIE', codigo: 'vn' },
  'Zâmbia': { sigla: 'ZAM', codigo: 'zm' },
  'Zimbábue': { sigla: 'ZIM', codigo: 'zw' },
};

Object.assign(PAISES_MAPA, {
  'Arsenal': { sigla: 'ARS', escudo: '/assets/clubes/arsenal.svg' },
  'África do Sul': { sigla: 'AFS', codigo: 'za' },
  'Alemanha': { sigla: 'ALE', codigo: 'de' },
  'Argélia': { sigla: 'AGL', codigo: 'dz' },
  'Argentina': { sigla: 'ARG', codigo: 'ar' },
  'Arábia Saudita': { sigla: 'ASA', codigo: 'sa' },
  'Austrália': { sigla: 'AUS', codigo: 'au' },
  'Áustria': { sigla: 'AUT', codigo: 'at' },
  'Bélgica': { sigla: 'BEL', codigo: 'be' },
  'Bósnia e Herzegovina': { sigla: 'BIH', codigo: 'ba' },
  'Brasil': { sigla: 'BRA', codigo: 'br' },
  'Cabo Verde': { sigla: 'CPV', codigo: 'cv' },
  'Canadá': { sigla: 'CAN', codigo: 'ca' },
  'Colômbia': { sigla: 'COL', codigo: 'co' },
  'Coreia do Sul': { sigla: 'CSU', codigo: 'kr' },
  'Costa do Marfim': { sigla: 'CMF', codigo: 'ci' },
  'Croácia': { sigla: 'CRO', codigo: 'hr' },
  'Curazao': { sigla: 'CUW', codigo: 'cw' },
  'Egito': { sigla: 'EGI', codigo: 'eg' },
  'Equador': { sigla: 'EQU', codigo: 'ec' },
  'Escócia': { sigla: 'ESC', codigo: 'gb-sct' },
  'Espanha': { sigla: 'ESP', codigo: 'es' },
  'Estados Unidos': { sigla: 'EUA', codigo: 'us' },
  'França': { sigla: 'FRA', codigo: 'fr' },
  'Gana': { sigla: 'GNA', codigo: 'gh' },
  'Haiti': { sigla: 'HAI', codigo: 'ht' },
  'Inglaterra': { sigla: 'ING', codigo: 'gb-eng' },
  'Irã': { sigla: 'IRA', codigo: 'ir' },
  'Iraque': { sigla: 'IRQ', codigo: 'iq' },
  'Japão': { sigla: 'JAP', codigo: 'jp' },
  'Jordânia': { sigla: 'JOR', codigo: 'jo' },
  'Marrocos': { sigla: 'MAR', codigo: 'ma' },
  'México': { sigla: 'MEX', codigo: 'mx' },
  'Nigéria': { sigla: 'NIG', codigo: 'ng' },
  'Noruega': { sigla: 'NOR', codigo: 'no' },
  'Nova Zelândia': { sigla: 'NZL', codigo: 'nz' },
  'Países Baixos': { sigla: 'PBA', codigo: 'nl' },
  'Panamá': { sigla: 'PAN', codigo: 'pa' },
  'Paraguai': { sigla: 'PAR', codigo: 'py' },
  'PSG': { sigla: 'PSG', escudo: '/assets/clubes/psg.svg' },
  'Portugal': { sigla: 'POR', codigo: 'pt' },
  'Qatar': { sigla: 'QAT', codigo: 'qa' },
  'República Democrática do Congo': { sigla: 'RDC', codigo: 'cd' },
  'República Tcheca': { sigla: 'RTC', codigo: 'cz' },
  'Senegal': { sigla: 'SEN', codigo: 'sn' },
  'Suécia': { sigla: 'SUE', codigo: 'se' },
  'Suíça': { sigla: 'SUI', codigo: 'ch' },
  'Tunísia': { sigla: 'TUN', codigo: 'tn' },
  'Turquia': { sigla: 'TUR', codigo: 'tr' },
  'Uruguai': { sigla: 'URU', codigo: 'uy' },
  'Uzbequistão': { sigla: 'UZB', codigo: 'uz' },
});

function obterSigla(nomePais) {
  const info = PAISES_MAPA[nomePais];
  return info ? info.sigla : nomePais.slice(0, 3).toUpperCase();
}

function obterUrlBandeira(nomePais) {
  const info = PAISES_MAPA[nomePais];
  if (!info) return null;
  if (info.escudo) return info.escudo;
  return `https://flagcdn.com/w80/${info.codigo}.png`;
}

function obterCodigoPais(nomePais) {
  const info = PAISES_MAPA[nomePais];
  return info ? info.codigo : null;
}
